### ISSUE TITLE
Regions don't seem to work

### ISSUE THREAD

**Issue by Pureshores** [fluttercommunity/flutter_google_places#112]
tried region: "country,administrative_area_level_1,administrative_area_level_2" but still returns results at a street level

**Comment by daiagi** [comment]
**from the [Places autocomplete documentation](https://developers.google.com/places/web-service/autocomplete?hl=en_US):**
In general, only a single type is allowed. The exception is that you can safely mix the geocode and establishment types, but note that this will have the same effect as specifying no types.

you can use types: ['(regions)'] instead
