### ISSUE TITLE
cities name in different language than english?

### ISSUE THREAD

**Issue by domizilver** [fluttercommunity/flutter_google_places#114]
i use this code to get city name but the city name shows only in english:

```
Future<Null> displayPrediction(Prediction p, ScaffoldState scaffold) async {
  if (p != null) {
    PlacesDetailsResponse detail = await _places.getDetailsByPlaceId(p.placeId);
    final city = detail.result.name;

    scaffold.showSnackBar(
      SnackBar(content: Text("${p.description} - $city")),
    );
  }
}
```
![Annotation 2020-05-07 230328](https://user-images.githubusercontent.com/61071761/81310973-5d7b5480-90b7-11ea-943e-8adbcc2ec458.png)

it shows Cologne, instead of Köln

**Comment by Bestfootballer** [comment]
In the method PlacesAutocomplete.show(), there's a parameter called "components".
Insert into it, [Component(Component.country, "it")];

The "it" String stands for the language. So in my case, is italian. In your case, set your language short name.

![image](https://user-images.githubusercontent.com/49185210/82188226-da939e80-98ed-11ea-9cf8-05fa524a95ae.png)
