### ISSUE TITLE
Error on select place

### ISSUE THREAD

**Issue by ErliSoares** [fluttercommunity/flutter_google_places#115]
`_debounce` time not closed on dispose

``` dart
void _onQueryChange() {
  if (_debounce?.isActive ?? false) _debounce.cancel();
  _debounce = Timer(Duration(milliseconds: widget.debounce), () {
    _queryBehavior.add(_queryTextController.text);
  });
}
```

[Line of code!](https://github.com/fluttercommunity/flutter_google_places/blob/master/lib/src/flutter_google_places.dart#L418)

E/flutter ( 8027): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: Bad state: Cannot add new events after calling close
E/flutter ( 8027): #0      _BroadcastStreamController.add (dart:async/broadcast_stream_controller.dart:251:24)
E/flutter ( 8027): #1      Subject._add (package:rxdart/src/subjects/subject.dart:141:17)
E/flutter ( 8027): #2      Subject.add (package:rxdart/src/subjects/subject.dart:135:5)
E/flutter ( 8027): #3      PlacesAutocompleteState._onQueryChange.<anonymous closure> (package:flutter_google_places/src/flutter_google_places.dart:418:22)
E/flutter ( 8027): #4      _rootRun (dart:async/zone.dart:1180:38)
E/flutter ( 8027): #5      _CustomZone.run (dart:async/zone.dart:1077:19)
E/flutter ( 8027): #6      _CustomZone.runGuarded (dart:async/zone.dart:979:7)
E/flutter ( 8027): #7      _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1019:23)
E/flutter ( 8027): #8      _rootRun (dart:async/zone.dart:1184:13)
E/flutter ( 8027): #9      _CustomZone.run (dart:async/zone.dart:1077:19)
E/flutter ( 8027): #10     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:1003:23)
E/flutter ( 8027): #11     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:23:15)
E/flutter ( 8027): #12     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:398:19)
E/flutter ( 8027): #13     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:429:5)
E/flutter ( 8027): #14     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)

**Comment by rodriigovieira** [comment]
I just received the same error. Strangely enough, a few days ago, with the same exact version, it was working just fine.

**Comment by Bestfootballer** [comment]
I've the same problem with previous version of the plugin. I've also updated Flutter to the latest version (1.17.1).
Which is your Flutter version?

**Comment by rodriigovieira** [comment]
1.17.1, the latest one on stable.

You downgraded to the 0.23 version of this plugin and the same error still occurs?

Are you positive you cleaned the project and is not still using the most recent version? I say that because I believe the line of code that is causing the error doesn’t exist on the previous versions.

**Comment by Bestfootballer** [comment]
Yes man, but I can try again this procedure and see if the error still occurs.

**Comment by superciccio** [comment]
by the way this fixes the issue

`    _debounce.cancel();`

**Comment by brtln** [comment]
thank you @superciccio ! This fixed it. Will you create a PR for that?

**Comment by bhanuka96** [comment]
> by the way this fixes the issue
> 
> ` @override
> void dispose() {
> super.dispose();
> 
> ```
> _places.dispose();
> **_debounce.cancel();**
> _queryBehavior.close();
> _queryTextController.removeListener(_onQueryChange);
> ```
> 
> }`

can you merge with live api?

**Comment by bhanuka96** [comment]
> I just received the same error. Strangely enough, a few days ago, with the same exact version, it was working just fine.
> 
> I downgraded to the 0.2.3 version and it worked fine.
> 
> It's just simply doing the following at `pubspec.yaml`:
> 
> ```
> dependencies:
>   flutter_google_places: 0.2.3
> ```

after downgrade

Because flutter_cache_manager >=1.2.0 <1.2.2 depends on rxdart ^0.23.1 and no versions of flutter_cache_manager match >1.2.2 <2.0.0, flutter_cache_manager >=1.2.0 <1.2.2-∞ or >1.2.2 <2.0.0 requires rxdart ^0.23.1.

And because flutter_cache_manager 1.2.2 depends on rxdart >=0.23.1 <0.25.0, flutter_cache_manager ^1.2.0 requires rxdart >=0.23.1 <0.25.0.

And because flutter_google_places >=0.2.3 <0.2.4 depends on rxdart ^0.22.0 and cached_network_image >=2.1.0 depends on flutter_cache_manager ^1.2.0, flutter_google_places >=0.2.3 <0.2.4 is incompatible with cached_network_image >=2.1.0.

**Comment by hoc081098** [comment]
Trying my fork
```yaml
dependency_overrides:
  flutter_google_places:
    git:
      url: https://github.com/hoc081098/flutter_google_places.git
      ref: 00159b26b6ccc58792b7273b8e637fefb46d1988
```

**Comment by juliansteenbakker** [comment]
Please use the following version:
```
  flutter_google_places:
    git:
      url: https://github.com/fluttercommunity/flutter_google_places
      ref: v0.3.2
```
