### ISSUE TITLE
Exception when closing Full screen PlacesAutocomplete view

### ISSUE THREAD

**Issue by shubhambansal** [fluttercommunity/flutter_google_places#121]
Using the following code to open full-screen google place search view. 

```
Prediction place = await PlacesAutocomplete.show(
        context: context,
        hint: 'Enter City name',
        apiKey: 'xyz',
        mode: Mode.fullscreen,
        onError: (error) => {
              print('Error in Place search = $error'),
              if (error is PlacesAutocompleteResponse)
                {print(error.errorMessage)}
            },
        language: 'en');
```

But after exiting from full-screen view I am getting the following exception. 

```
[ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: Bad state: Cannot add new events after calling close
    #0      _BroadcastStreamController.add (dart:async/broadcast_stream_controller.dart:251:24)
    #1      Subject._add (package:rxdart/src/subjects/subject.dart:141:17)
    #2      Subject.add (package:rxdart/src/subjects/subject.dart:135:5)
    #3      PlacesAutocompleteState._onQueryChange.<anonymous closure> (package:flutter_google_places/src/flutter_google_places.dart:418:22)
    #4      _rootRun (dart:async/zone.dart:1180:38)
    #5      _CustomZone.run (dart:async/zone.dart:1077:19)
    #6      _CustomZone.runGuarded (dart:async/zone.dart:979:7)
    #7      _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1019:23)
    #8      _rootRun (dart:async/zone.dart:1184:13)
    #9      _CustomZone.run (dart:async/zone.dart:1077:19)
    #10     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:1003:23)
    #11     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:23:15)
    #12     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:398:19)
    #13     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:429:5)
    #14     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
```

Please help me understand in case I am doing something wrong.

**Comment by ivanespitiac** [comment]
@shubhambansal The error in the method "_onQueryChange" inside the widget is trying to make this "_queryBehavior.add(_queryTextController.text);" bus the "_queryBehavior" was previously closed, if you can clone the proyect or use the class for put a conditional like this works.
````
if (!_queryBehavior.isClosed) {
    _queryBehavior.add(_queryTextController.text);
}
````

**Comment by shubhambansal** [comment]
@ivanespitiac Thanks for your answer. 

If I understood it correctly, I have to clone the project and add this check manually in order to solve this issue?  If this is the case, can't this be taken care from your side in the next release of this lib?

Please let me know so accordingly, I'll make my decision.

Thanks.

**Comment by ivanespitiac** [comment]
@shubhambansal maybe i can make a PR for this issue, but we have to wait that will be approved, i will do it! meanwhile it's faster for you clone the project.

**Comment by ishuacharis** [comment]
hi @ivanespitiac i have the same issue raised by @shubhambansal using flutter_google_places although i didn't clone the repo but I edited the package to fix the changes I am still getting the same error I hope you fix it soon.

**Comment by ishuacharis** [comment]
Hi @ivanespitiac  I must confess you did a very great job as regard this wonderful pub dev package.

**Comment by ivanespitiac** [comment]
@ishuacharis Hi! thanks for your comments, i'm not the creator jeje i'm only fix the issue in this case, the changes was merged, but we have to wait for next release get this fixes.

**Comment by shubhambansal** [comment]
@ivanespitiac Thanks :)

**Comment by shubhambansal** [comment]
@ivanespitiac didn't you publish the new changes to pub.dev ?  Because I am not able to found a new version with this fix.

**Comment by MachariaK** [comment]
I have this problem as well.

**Comment by Victor-Dev77** [comment]
same

**Comment by entrpn** [comment]
same. Please fix.

**Comment by Ochieng424** [comment]
Can somebody please explain how i can fix this issue in the current release. I have added the conditional check but i've still got the error

**Comment by MuhammamdArslanKhan** [comment]
facein same issue:" Unhandled Exception: Bad state: Cannot add new events after calling close"

**Comment by hoc081098** [comment]
# Trying this: https://pub.dev/packages/flutter_google_places_hoc081098

- Migrated to null-safety.
- Updated dependencies to latest release.
- Refactoring by using RxDart for more power.
- Fixed many issues.
- Applied flutter_lints.
- Refactored example, migrated to Android v2 embedding.

**Comment by juliansteenbakker** [comment]
I have updated this package, please use the following:

```
  flutter_google_places:
    git:
      url: https://github.com/fluttercommunity/flutter_google_places
      ref: v0.3.2
```
