### ISSUE TITLE
Handshake Exception

### ISSUE THREAD

**Issue by vishalkevin11** [fluttercommunity/flutter_google_places#123]
When connected on mobile network we face this handshake exception
Unhandled Exception: HandshakeException: Handshake error in client (OS Error:
	CERTIFICATE_VERIFY_FAILED: ok(handshake.cc:354))

**Comment by vedangdate** [comment]
Any leads on this?

**Comment by juliansteenbakker** [comment]
Can you provide output of `fluttter doctor -v`, and also some info on which device you are getting this error on?
