### ISSUE TITLE
Unable to get back the results from the api

### ISSUE THREAD

**Issue by amitgupta0294** [fluttercommunity/flutter_google_places#132]
I am having the same problem. Done everything as given in the docs of flutter_google_place but not able to get any result back. Google cloud platform is showing 100% error for the api. Do i need to enable billing even for testing ?

**Comment by arteevraina** [comment]
> I am having the same problem. Done everything as given in the docs of flutter_google_place but not able to get any result back. Google cloud platform is showing 100% error for the api. Do i need to enable billing even for testing ?

Yes

**Comment by KevMorelli** [comment]
Hi, 
yes, enable billing is necessary for even testing. I will change the example to throw that specific error to prevent confusion in the future
