### ISSUE TITLE
after pick location throw this

### ISSUE THREAD

**Issue by joharputr** [fluttercommunity/flutter_google_places#134]
![image](https://user-images.githubusercontent.com/32647004/96532153-7ec2ac80-12b5-11eb-896f-66d3b45d57cc.png)

**Comment by Hasankanso** [comment]
I have the same problem, it happens when I type any letter, and go back before getting any response

**Comment by newit-huytt** [comment]
There is any way to fix it??? T.T

**Comment by KevMorelli** [comment]
unable to reproduce, can you test with version 0.3.0 ?
