### ISSUE TITLE
Please update to rxdart ^0.26.0!

### ISSUE THREAD

**Issue by r0mmen** [fluttercommunity/flutter_google_places#153]
Hey,

clould you please update the dependency to rxdart to version 0.26.0? I am using geoflutterfire together with this lib and they're no longer matching :-(

**Comment by Beautylivery** [comment]
Just run into the same issue

**Comment by r0mmen** [comment]
Work around: Fork the repo and just update the rxdart lib by yourself. Then use your fork in the pubspec.yaml
