### ISSUE TITLE
Result don't show on my screen

### ISSUE THREAD

**Issue by guijacobus2** [fluttercommunity/flutter_google_places#159]
I am having the following issue: I have a Flutter project with a Text Form Field where I am calling the flutter_google_places API.
I can see the new screen when I click on it, the Powered By Google Logo, but when I search any address, I can't see any results, only a loading bar under the search bar, but no results, just a blank screen.

This is the code I am using for now:

TextFormField(
                          decoration: textInputDecoration.copyWith(
                            hintText: "Enter Company Address",
                            prefixIcon: Icon(Icons.map),
                          ),
                          onTap: () async {
                            Prediction p = await PlacesAutocomplete.show(
                              context: context,
                              apiKey: kGoogleApiKey,
                              mode: Mode.fullscreen,
                            );
                            return p;
                          },
                          validator: (val) =>
                              val.isEmpty ? 'Enter address' : null,
                          onChanged: (val) {
                            setState(() => address = val);
                          },
                        ),

**Comment by muhammadsaddamnur** [comment]
same issue

**Comment by KevMorelli** [comment]
Did you replaced kGoogleApiKey value with your API key and enabled billing?

**Comment by guijacobus2** [comment]
@KevMorelli yes all API’s are enabled, billing account active, replaced by my apy... Don’t know what’s wrong

**Comment by KevMorelli** [comment]
Any info on the debug console?

**Comment by muhammadsaddamnur** [comment]
i try get API in postman with my key is fine, i have result from API.
but when use this package i don't have result or error on debug console.

**Comment by guijacobus2** [comment]
I got it working, had to set the strictbound to false and radius to 100000
