### ISSUE TITLE
update rx_dart version to 0.27.1

### ISSUE THREAD

**Issue by prajwal27** [fluttercommunity/flutter_google_places#166]
from rx_dart 0.27, there's a breaking change. Hence projects depending on this package as well as rx_dart might face issues.

**Comment by hoc081098** [comment]
Try this: https://pub.dev/packages/flutter_google_places_hoc081098

**Comment by prajwal27** [comment]
@hoc081098  does it work with latest version of rx_dart?

**Comment by hoc081098** [comment]
> @hoc081098  does it work with latest version of rx_dart?
> 

Yes

**Comment by juliansteenbakker** [comment]
Duplicate of #164. Expect an update soon.
