### ISSUE TITLE
Flutter Web - Can't google place autocomplete to work unless using proxy url.

### ISSUE THREAD

**Issue by DavidHCox** [fluttercommunity/flutter_google_places#174]
**Has anybody got the google place working without using the proxy url?**

Right now we are using 'cors-anywhere.herokuapp.com' as the proxy url and works with limitations, but in the long run we just do not want to use one.

Is there something that I am not understanding about the web that requires a proxy url?

**Comment by sajithlaldev** [comment]
yes

**Comment by aliaafreen** [comment]
still needed proxy url?
I am using flutter_google_places: ^0.3.0 but still i am getting error of XMLHttpRequest error for flutter web.

**Comment by jpetro416** [comment]
I'm using flutter_google_places: ^0.3.0 
Getting error:
```

Error: XMLHttpRequest error.
    C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/patch/core_patch.dart 908:28                get current
packages/http/src/browser_client.dart 69:22  
```

**Comment by blackdye** [comment]
I'm using flutter_google_places: ^0.3.0 and I havent been able to find a solution
Error:


```
Error: XMLHttpRequest error.
    C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/patch/core_patch.dart 908:28                get current
packages/http/src/browser_client.dart 69:22  
```

**Comment by timndichu** [comment]
Any solution to this?

**Comment by juliansteenbakker** [comment]
For now there is no solution since this is not supported by google. also this is a duplicate of #93
