### ISSUE TITLE
[Doc] android api key is not working with map android sdk

### ISSUE THREAD

**Issue by reeteshkumar39** [fluttercommunity/flutter_google_places#18]
this gives error:::This IP, site or mobile application is not authorized to use this API key

**Comment by KarimMohamed2005** [comment]
+1 giving it to me

**Comment by KarimMohamed2005** [comment]
Solved replace Places Android Sdk and Places iOS Sdk with Places Sdk

**Comment by lejard-h** [comment]
I mark this issue as a documentation issue

This should be in readme.

The widget is using the google webservice so the api key need to be a Places API for web key

**Comment by dkobia** [comment]
@lejard-h, using a web key has one obvious problem -- it can't be restricted and if someone pulls the api key from your app, they too can use it.

**Comment by zeshuaro** [comment]
I've made a comment on a related issue https://github.com/fluttercommunity/flutter_google_places/issues/127#issuecomment-751307160 about this which should solve the described issue.
