### ISSUE TITLE
How to clear update input field?

### ISSUE THREAD

**Issue by naumanahmed19** [fluttercommunity/flutter_google_places#29]
Is there any way to set or clear input field? For example, I have a button to clear input filed in the app bar. _queryTextController is not accessible may b there should be a setter.

**Comment by KevMorelli** [comment]
Implemented by @Asdamp on PR #71

**Comment by KevMorelli** [comment]
Fixed on [0.2.4](https://pub.dev/packages/flutter_google_places)
