### ISSUE TITLE
How to add this with my custom text field

### ISSUE THREAD

**Issue by delphiy** [fluttercommunity/flutter_google_places#38]
I have two text field , from address and to address. How to show prediction addresses when user type in

**Comment by MattL-NZ** [comment]
I agree that there should be a way to do this. @lejard-h Can you please provide an update?

**Comment by cadrogui** [comment]
any solution for this issue??

thanks.

**Comment by cadrogui** [comment]
here is the closest aproach that ive found:

https://github.com/lejard-h/flutter_google_places/blob/master/lib/src/places_autocomplete_form_field.dart

**Comment by Letalus** [comment]
Why are you guys not simply just picking the functionality out of this packages, which you need? I just picked all the functionality out, which I needed to make the prediction work, and then implemented my own code. Idk, if you have problems with this, you can ask me ;)
