### ISSUE TITLE
Provide selective data for better billing 

### ISSUE THREAD

**Issue by feinstein** [fluttercommunity/flutter_google_places#45]
The new Places API Billing model has free basic data and paid extra data (like contact data) as seen here: https://developers.google.com/places/android-sdk/usage-and-billing

I took a quick look at the samples and couldn't see how to pass which data I want from the API. 

Google just announced a depreciation on its Android and iOS Places API, the new Android API can be seen here: https://developers.google.com/places/android-sdk/client-migration and this link shows how we can select which data we want back from the API for better billing (including session Tokens). 

It would be nice to have a similar API here in Flutter (although I miss the ability to cancel ongoing networking operations that are not more relevant).

**Comment by Craaab** [comment]
Same question here.

**Comment by juliansteenbakker** [comment]
This is not handled in this library but in [google_maps_webservices](https://github.com/lejard-h/google_maps_webservice)
