### ISSUE TITLE
update the http version

### ISSUE THREAD

**Issue by noisytempo** [fluttercommunity/flutter_google_places#48]
Currently http version used is 0.11.3
Available version is 0.12.0

Problem faced due to old version of http package is =>
 Because every version of rozana_api_service from git depends on jaguar_retrofit 2.8.6 which depends on http ^0.12.0, every version of rozana_api_service from git requires http ^0.12.0.

And because flutter_google_places >=0.2.0 depends on http ^0.11.3, rozana_api_service from git is incompatible with flutter_google_places >=0.2.0.
So, because rozana_customer_app depends on both flutter_google_places 0.2.0 and rozana_api_service from git, version solving failed.

**Comment by Mallikarjun-0369** [comment]
Am also facing issues with legacy http package.

**Comment by vision8tech** [comment]
Same issue here while trying to use it in a project already having `global_configuration` package.

**Comment by Firman95** [comment]
Same issue here while trying to use it in a project already having flutter_advanced_networkimage
package.

**Comment by noisytempo** [comment]
use this repo to avoid the issue:

> https://github.com/noisytempo/flutter_google_places

replace your package.yaml file

from:
```
flutter_google_places: 0.2.0
```

to:
```
flutter_google_places:
    git:
      url: https://github.com/noisytempo/flutter_google_places.git
```

**Comment by awhitford** [comment]
The `http` dependency is already `0.12.0+2` now, so I'm guessing that this issue can be closed.
