### ISSUE TITLE
No results coming back

### ISSUE THREAD

**Issue by levimatheri** [fluttercommunity/flutter_google_places#51]
I have been using this dependency for a while now and it used to work. Now all of a sudden, no results are coming back even though I am using the correct api key from Google and have even tried a new api key with no success. I also tried updating flutter_google_places to the latest version with no luck.

**Comment by julianmarangoni** [comment]
Was having same issue, was working at first, then results just stopped showing. Turns out my access to the API was being denied.

    flutter_google_places.dart:

    Future<Null> doSearch(String value) async {
    if (mounted && value.isNotEmpty) {
      setState(() {
        _searching = true;
      });

      final res = await _places.autocomplete(
        value,
        offset: widget.offset,
        location: widget.location,
        radius: widget.radius,
        language: widget.language,
        sessionToken: widget.sessionToken,
        types: widget.types,
        components: widget.components,
        strictbounds: widget.strictbounds,
      );

      if (res.errorMessage?.isNotEmpty == true || <---------- ACCESS DENIED MESSAGE HERE
          res.status == "REQUEST_DENIED") {
        onResponseError(res);
      } else {
        onResponse(res);
      }
    } else {
      onResponse(null);
    }
     }

I didn't have the API enabled. (don't know why it was working before). Was getting the following error message:

> This API project is not authorized to use this API. Please ensure this API is activated in the Google Developers Console: https://console.developers.google.com/apis/api/places_backend?project=_

After enabling the API, I started getting:

> You have exceeded your daily request quota for this API. If you did not set a custom daily request quota, verify your project has an active billing account: http://g.co/dev/maps-no-account

And according to https://stackoverflow.com/a/52545293, **you need to enable billing on your account, even if you are only using the free quota.**

**Comment by SimonHeimer** [comment]
I am trying to change language and country but I still only retrieve french results even though I changed the parameters.

Prediction p = await PlacesAutocomplete.show(
      context: context,
      apiKey: kGoogleApiKey,
      onError: onError,
      mode: _mode,
      language: "sv",
      components: [Component(Component.country, "sv")],

**Comment by KevMorelli** [comment]
Solved by @julianmarangoni

**Comment by erperejildo** [comment]
If we need to activate the billing on our account that some kind of important info we should have on the README
