### ISSUE TITLE
how to set a restriction of autocomplete result 

### ISSUE THREAD

**Issue by DanielGiKim** [fluttercommunity/flutter_google_places#52]
Hello.
Is it possible to set city restriction of autocomplete result? 
I know this code( Component(Component.country, "uk") )  is for the country, but I need to have a function that can find addresses in only restricted city and country. 
I have tried with Component(Component.locality, "London") and Component(Component.administrativeArea, "London"), but it is showing no results.
anyone ideas?
Thank you

**Comment by SimonHeimer** [comment]
administrativearea doesnt seems to work. However you must choose country "uk" . You cannot choose cities.

**Comment by JosLuna98** [comment]
Hello, is there any way to get a restriction for cities please?

**Comment by LucasTejero** [comment]
> Hello, is there any way to get a restriction for cities please?

you need to add types: ["(cities)"] ,

**Comment by harshmantri88** [comment]
@LucasTejero Thanks, It's work, helpful for me.
