### ISSUE TITLE
No named parameter With name sessionToken

### ISSUE THREAD

**Issue by eopeter** [fluttercommunity/flutter_google_places#55]
Getting below error when updated to v0.2.2. Any help is appreciated

---------------
compiler message:
file:///Users/Account/Development/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_google_places-0.2.2/lib/src/flutter_google_places.dart:375:9: Error: No named parameter with the name 'sessionToken'.
        sessionToken: widget.sessionToken,
        ^^^^^^^^^^^^

**Comment by KevMorelli** [comment]
Impossible to reproduce in 0.23/0.24
