### ISSUE TITLE
Geoflutterfire and Flutter google places, rxdart conflict

### ISSUE THREAD

**Issue by rysnt** [fluttercommunity/flutter_google_places#58]
Running "flutter packages get" in xplorr-v2...                  
Because geoflutterfire 2.0.3+2 depends on rxdart ^0.20.0 and flutter_google_places ^0.1.3 depends on rxdart ^0.19.0, geoflutterfire 2.0.3+2 is incompatible with flutter_google_places ^0.1.3.
So, because xplorr_v2 depends on both geoflutterfire 2.0.3+2 and flutter_google_places ^0.1.4, version solving failed.

**Comment by awhitford** [comment]
Yeah, I'm running into this too...  Can we please get a version upgrade release?

**Comment by rysnt** [comment]
you mean flutter version ? if is that...
Flutter (Channel master, v1.5.9-pre.174, on Linux, locale en_US.UTF-8)
    • Flutter version 1.5.9-pre.174
    • Framework revision fbe11671a4 (6 hours ago), 2019-05-07 18:13:39 -0400
    • Engine revision 149b7b8981
    • Dart version 2.3.0 (build 2.3.0-dev.0.5 a8b6e18b62)

**Comment by awhitford** [comment]
@rysnt I meant to ask the maintainers for a new release with updated dependencies.  I submitted a pull request.  🤞

**Comment by cobra811** [comment]
rxdart 0.22.0 is needed as a dependency

**Comment by awhitford** [comment]
Pull request #61 updates `rxdart`.
