### ISSUE TITLE
How to set Logo in PlacesAutocompleteField ?

### ISSUE THREAD

**Issue by mappple** [fluttercommunity/flutter_google_places#59]
I know the option is available in PlacesAutocomplete, but the parameters of  PlacesAutocompleteField still cannot access the Logo Widget.

Thanks for any help!

**Comment by dimpleagola** [comment]
can i remove google place logo????
I want powered by  Google image remove. But i don't know how can possible in flutter.

**Comment by emailsubjekt** [comment]
Yeah, please give support for inputting your own logo please!

**Comment by KevMorelli** [comment]
It will be good to combine this and #77

**Comment by abhijithvijayan** [comment]
Any updates on this issue?

**Comment by ccc-dvansevenant** [comment]
Check here first?

https://developers.google.com/maps/documentation/places/web-service/policies#powered
