### ISSUE TITLE
'Duration' can't be assigned to the parameter type 'Stream<dynamic> Function(String)'

### ISSUE THREAD

**Issue by awhitford** [fluttercommunity/flutter_google_places#60]
I just tried to add this to my project, but now it doesn't build.  Getting the following error:
```
Compiler message:
file:///Users/anthony/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_google_places-0.2.2/lib/src/flutter_google_places.dart:359:25: Error: The
argument type 'Duration' can't be assigned to the parameter type 'Stream<dynamic> Function(String)'.
 - 'Duration' is from 'dart:core'.
 - 'Stream' is from 'dart:async'.
Try changing the type of the parameter, or casting the argument to 'Stream<dynamic> Function(String)'.
        .debounce(const Duration(milliseconds: 300))
                        ^
```

**Comment by awhitford** [comment]
This looks like it is due to a breaking change made by Dart 0.22; I had to force an upgrade because of issue #58.
> Breaking Change: debounce is now split into debounce and debounceTime.

**Comment by mukai154** [comment]
Having the same issue

**Comment by mukai154** [comment]
Fixed it
Works fine now 
https://github.com/mukai154/flutter_google_places

**Comment by mukai154** [comment]
lib/src/flutter_google_places.dart

**Comment by lejard-h** [comment]
Fix https://github.com/fluttercommunity/flutter_google_places/pull/61
It will be in the next release
