### ISSUE TITLE
Update to rxdart 0.22.0

### ISSUE THREAD

**Issue by momsenmeister** [fluttercommunity/flutter_google_places#66]
Hi,
I use some packages that depend on rxdart 0.22.0.
Is it possible for you to update the dependency to rxdart from 0.21.0 to 0.22.0?
Thanks a lot,
Michael

**Comment by ruhanijeb** [comment]
Please update . i am also stuck here in my current project.

**Comment by lejard-h** [comment]
Fix with https://github.com/fluttercommunity/flutter_google_places/pull/61
Will be in the next release
