### ISSUE TITLE
[dart] Undefined class 'GoogleMapsPlaces'.

### ISSUE THREAD

**Issue by mohammed932** [fluttercommunity/flutter_google_places#70]
<img width="980" alt="Screen Shot 2019-06-25 at 12 40 50 PM" src="https://user-images.githubusercontent.com/24191439/60092365-245c1f00-9747-11e9-8633-bf3caec334de.png">

**Comment by mohammed932** [comment]
and also this error occur "[dart] Undefined class 'Prediction'."
in this line code =======> Prediction p = await PlacesAutocomplete.show

**Comment by pratik037** [comment]
@mohammed932 checkout the example from the stackoverflow link [here](https://stackoverflow.com/questions/55870508/how-to-create-a-simple-google-maps-address-search-with-autocomplete-in-flutter-a)
You can the find the example code in the answer which will solve your issue.

**Comment by mayankjanmejay** [comment]
Hello, 
I had previously successfully used this plugin in my app about 2 months ago. I didn't have this error before but I suddenly now do have this error now and Its not getting resolved with the solution mentioned in stackoverflow. 

Please help.

**Comment by pratik037** [comment]
> Hello,
> I had previously successfully used this plugin in my app about 2 months ago. I didn't have this error before but I suddenly now do have this error now and Its not getting resolved with the solution mentioned in stackoverflow.
> 
> Please help.

You might wanna check the new docs as they must have updated some things.

**Comment by Shivkant23** [comment]
flutter_google_places_autocomplete 0.1.3
with method showGooglePlacesAutocomplete()
not showing any error with your code.

**Comment by pratik037** [comment]
> flutter_google_places_autocomplete 0.1.3
> with method showGooglePlacesAutocomplete()
> not showing any error with your code.

Whom are you talking to my friend? Quote the reply and then answer :)

**Comment by mayankjanmejay** [comment]
Hello

> flutter_google_places_autocomplete 0.1.3
> with method showGooglePlacesAutocomplete()
> not showing any error with your code.
> 
> Whom are you talking to my friend? Quote the reply and then answer :)

Hello Pratik, 

Thank you for looking into this. It seems to have been something with my flutter pub cache once I cleared the cache it started working again.

**Comment by IRuFFeYI** [comment]
I had the same Problem. I needes this import "import 'package:google_maps_webservice/places.dart';". Then everything worked fine.

**Comment by yudi43** [comment]
use import 'package:google_maps_webservice/places.dart'; along with, import 'package:flutter_google_places/flutter_google_places.dart';

**Comment by KevMorelli** [comment]
Resolved by @IRuFFeYI and @yudi43
