### ISSUE TITLE
Exception has occurred. JsonUnsupportedObjectError (Converting object to an encodable object failed: Instance of 'PlaceDetails')

### ISSUE THREAD

**Issue by rajeshzmoke** [fluttercommunity/flutter_google_places#75]
cannot convert the `PlacesDetailsResponse` to `JSON` String

when converting the `PlacesDetailsResponse` using  `json.encode(placesDetailsResponseData)` from `dart:convert` i get this error

`Exception has occurred. JsonUnsupportedObjectError (Converting object to an encodable object failed: Instance of 'PlaceDetails')`

**Comment by plugin-service** [comment]
We are getting the same issue when using the example code

**Comment by juliansteenbakker** [comment]
I have updated this package, please use the following:

  flutter_google_places:
    git:
      url: https://github.com/fluttercommunity/flutter_google_places
      ref: v0.3.2
