### ISSUE TITLE
flutter_google_places autocomplete shows search results once in while

### ISSUE THREAD

**Issue by KNehe** [fluttercommunity/flutter_google_places#78]
My implemenatation
 TextField(
                       decoration: InputDecoration(
                           hintText: _hintPickUpPlace,
                           border: InputBorder.none,
                           icon: Icon(Icons.search,color: Colors.white,),
                           hintStyle: TextStyle(fontSize: 18,color: Colors.white,fontWeight: FontWeight.bold)
                       ),
                       onTap: (){
                         showGooglePlaceWidget();
                         _state = States.pickUpSate;
                       },
                     )

 Future<void> showGooglePlaceWidget() async
  {
              Prediction p = await PlacesAutocomplete.show(

                context: context,
                apiKey: kGoogleApiKey,
                mode: Mode.overlay,
                language: "en",
                radius: _center == null ? null : 10000000
            );
}

**Comment by KNehe** [comment]
When i search a place it either displays it first time or not. Sometimes it doesn't show anything.At times it shows after several tries.

**Comment by abbasidaniyal** [comment]
I'm experiencing the same issue

**Comment by vinaypuranik** [comment]
Yes, I am experiencing the same as well. Is there any solution for this.

**Comment by abbasidaniyal** [comment]
Enable the places api. I had the geocoding api enable only and thus was experiencing this error. This might fit it

**Comment by vinaypuranik** [comment]
@abbasidaniyal Places API is already enabled, it used to work earlier, now, since yesterday I am facing this error

**Comment by abbasidaniyal** [comment]
Check your usage limits. It can also be due to slow internet.

**Comment by KNehe** [comment]
@abbasidaniyal  i enable places API and my internet is pretty fast but same issue

**Comment by vinaypuranik** [comment]
It fails due to 4xx errors as per the graphs shown in GCP console.

**Comment by vinaypuranik** [comment]
@here Any solution for this?

**Comment by wakandan** [comment]
@vinaypuranik did you check your quota limit? For free account the limit rate is pretty low. I had this issue before until I upgrade my account to paid.

**Comment by emrade** [comment]
I had the same issue, but after enabling billing for the project it was solved.

**Comment by juliansteenbakker** [comment]
I'm closing this for now because of activity. Please upgrade to the latest version and feel free to comment if this issue still exists.
