### ISSUE TITLE
A newly added Google Place not being found in a search?

### ISSUE THREAD

**Issue by itomicspaceman** [fluttercommunity/flutter_google_places#79]
Hello,

As a Google Local Guide I recently (about a week ago) and successfully added a listing for "Haymoor Sports Club"

https://goo.gl/maps/xJxe4h8xd2erGcRy8

![Haymoor Sports Club - Google Maps](https://user-images.githubusercontent.com/46665538/64089565-ebb17500-cd89-11e9-8b27-612a3479c9f3.png)

Despite this being about a week ago, I'm still not able to find this place when I perform a search for it in our Flutter app using flutter_google_places. It just doesn't show up.

What am I missing? I'm guessing that flutter_google_places is working fine, and that I'm misunderstanding the relationship between places I add to Google Maps, and how Google Places actually works?

Thanks,

Ross

**Comment by juliansteenbakker** [comment]
This would be an issue with the google api and not this package.
