### ISSUE TITLE
Web compatibility

### ISSUE THREAD

**Issue by juanjoserodrigolazaro** [fluttercommunity/flutter_google_places#83]
hello i want to make it work on flutter web, there is a way to make it?

**Comment by abbasidaniyal** [comment]
I have just opened a new PR with added support. 
https://github.com/fluttercommunity/flutter_google_places/pull/86

**Comment by abbasidaniyal** [comment]
I don't know about the first question.

For the second part, you can write a widget that implements the searching on change and contribute!
It's purely Flutter code and should be a 30 min job!
