### ISSUE TITLE
Search a place near by user's location. 

### ISSUE THREAD

**Issue by parth22** [fluttercommunity/flutter_google_places#91]
How to search a places near by user's location. i mean the place suggested by flutter_google_places are near by user's location.
```
final placeList = await PlacesAutocomplete.show(
      context: context,
      apiKey: kGoogleApiKey,
      language: 'en',
      mode: Mode.overlay,
      radius: 30.0,
    );
```

**Comment by evanave** [comment]
Radius should be in meters, but setting strictbounds: false doesn't allow results outside of the radius to show up.
