### ISSUE TITLE
Old version of rxdart

### ISSUE THREAD

**Issue by sanisloandras** [fluttercommunity/flutter_google_places#94]
Hi!

Can you guys please update the version of rxdart?

I'm getting this error:
`Because flutter_google_places 0.2.3 depends on rxdart ^0.22.0 and bkk_flutter depends on rxdart ^0.23.0, flutter_google_places 0.2.3 is forbidden.`

Thanks

**Comment by momoDragon** [comment]
having the same isssue 
Because flutter_google_places >=0.2.3 depends on rxdart ^0.22.0 and geoflutterfire 2.0.3+7 depends on rxdart ^0.23.1, flutter_google_places >=0.2.3 is incompatible with geoflutterfire 2.0.3+7.
@lejard-h  please take note

**Comment by TommyLCox** [comment]
Same.. just bumping rxdart to ^0.23.0 would help

**Comment by caiogranero** [comment]
Same problem here

**Comment by AustinDLatture** [comment]
Same issue here. Would love a bump.

**Comment by TommyLCox** [comment]
I simply forked and updated RxDart in the pubspec.. only took a few minutes.

**Comment by KevMorelli** [comment]
Fixed on [0.2.4](https://pub.dev/packages/flutter_google_places)
