### ISSUE TITLE
Not all the search location work

### ISSUE THREAD

**Issue by ziasultan2** [fluttercommunity/flutter_google_places#96]
When I try to search some location it doesn't give me lat, long it shows this error 
Ex. Burger King, Hylan Boulevard, Staten Island, NY, USA
Please have a look and let me know how to solve this and thank you for this package. It saves a lots of time of mine

[VERBOSE-2:ui_dart_state.cc(148)] Unhandled Exception: PlatformException(Error 8, kCLErrorDomain, The operation couldn’t be completed. (kCLErrorDomain error 8.))
#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:569:7)
#1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:316:33)
<asynchronous suspension>
#2      LocalGeocoding.findAddressesFromQuery (package:geocoder/services/local.dart:18:43)
<asynchronous suspension>
#3      _MapLocationState.displayPrediction (package:user/ui/order/map_location.dart:154:42)
<asynchronous suspension>
#4      _MapLocationState.build.<anonymous closure> (package:user/ui/order/map_location.dart:123:21)
<asynchronous suspension>
#5      _TextFieldSelectionGestureDetectorBuilder.onSingleTapUp (package:flutter/src/material/text_field.dart:105:21)
#6      _TextSelectionGestureDetectorState._handleTapUp (package:flutter/src/widgets/text_selection.dart:1264:16)
#7      TapGestureRecognizer._check<…>

**Comment by juliansteenbakker** [comment]
I'm closing this for now because of activity. Please upgrade to the latest version and feel free to comment if this issue still exists.
