### ISSUE TITLE
pub get failed

### ISSUE THREAD

**Issue by rahuldange09** [fluttercommunity/flutter_google_places#99]
Can you please update your dependencies to latest version.
because i'm getting this error
`pub get failed (1; So, because fraazo depends on both flutter_bloc ^3.1.0 and flutter_google_places ^0.2.3, version solving failed.)`

**Comment by leechieh** [comment]
Also the rxdart please.
`Because flutter_google_places >=0.2.3 depends on rxdart ^0.22.0 and app depends on rxdart ^0.23.1, flutter_google_places >=0.2.3 is forbidden.`

**Comment by guigzp** [comment]
Any update on this? The dependency on rxdart ^0.22.0 is troublesome

**Comment by KevMorelli** [comment]
Fixed on [0.2.4](https://pub.dev/packages/flutter_google_places)
